### ISSUE TITLE
Does not work if the DOM has not been parsed yet

### ISSUE THREAD

**Issue by groe** [zafree/pilpil#1]
When I include the `<script>` in the `<head>` of a page, it's not working because it executes before the DOM has been parsed ompletely (`document.querySelectorAll('.progressiveMedia')` returns an empty array).

With jquery this could easily be handled with `$(document).ready(...)`. In plain JS it seems to be [trickier](http://stackoverflow.com/questions/9899372/pure-javascript-equivalent-to-jquerys-ready-how-to-call-a-function-when-the) though.

**Comment by zafree** [comment]
For now, add `<script>` to bottom of page. 
Then next, I'll try to fixed it with plain JS :)

**Comment by groe** [comment]
Thanks a lot, @zafree!
