### ISSUE TITLE
Works only for visible images

### ISSUE THREAD

**Issue by groe** [zafree/pilpil#3]
For images that are not visible when the script executes (i.e. their parent elements are hidden via CSS), the max-width and max-height attributes of the ratio placeholder are set to `0` permanently (because `offset<Width|Height>`  are 0 at that time). This results in images permanently being hidden even when their parent container is made visible at some later point.

A typical scenario for this would be image sliders or carousels where only one image is visible at a time. It would be great if pilpil could support this kind of scenario.

A possible solution would be to offer a global method that users of the library can call to recompute widths and heights.

Btw: Really great work!

**Comment by zafree** [comment]
Yah! You made me worried. Let me think what I can do. And please, you also try to think of something. @groe

**Comment by groe** [comment]
No worries @zafree :)

How about adding a method that recalculates and sets the width/height again?

For instance, for a [bootstrap carousel](http://getbootstrap.com/javascript/#carousel) it could be used like:

``` js
$(function() {
  $('#myCarousel').carousel()
  // whenever a slide becomes visible
  $('#myCarousel').on('slide.bs.carousel', function (e) {
    // update all .aspectRatioPlaceholders in e.relatedTarget
    pilpil.update(e.relatedTarget);
  })
});
```

**Comment by zafree** [comment]
@groe the hero :)
