### ISSUE TITLE
Adding New Feature

### ISSUE THREAD

**Issue by MTayyabHanif** [zafree/pilpil#6]
Hi,
 without any formality, i just want to say that ...like you said on **description** "as seen on Medium."
 Unlike this library, the images on Medium's website  loads only when user scroll up on them.
 On this library, the images first show the blur-canvas and after that the full-size image loads, 
 but it doesn't speeds up the loading time because the original image also start loading right after the smaller one finished.
I hope you get my point.
what are your thoughts on this? :) ^_^

P.S Sorry for my bad English

**Comment by zafree** [comment]
@MTayyabHanif Apologies for the delay in updating. I got caught up with other projects, but I'm back on track now and ready to contribute to open source again.

Check out the latest update! I've implemented the IntersectionObserver API, so images will now load only when they're in the viewport.
