### ISSUE TITLE
Apply Source code in JSbin

### ISSUE THREAD

**Issue by jt4000** [zafree/pilpil#7]
Hello!

I have downloaded the source code and it doesn't work when I follow the instructions about how to use the Pilpil

Is it possible to upload the source code to the "http://jsbin.com/"? Is is easier to understand how the sourcecode is built.

Thank you!

**Comment by MTayyabHanif** [comment]
The demo website is working, isn't it?
[Demo link](https://zafree.github.io/pilpil)

**Comment by MTayyabHanif** [comment]
Or you can check here, I uploaded it's source code. So you can watch all the stuff 
[jsfiddle Demo](https://jsfiddle.net/mnusc3a8/)
