### ISSUE TITLE
Setting the width & height automatically inherit its parent?

### ISSUE THREAD

**Issue by squalvj** [zafree/pilpil#8]
id like to ask, how to make the original width and height set inherit to their respective parent? i mean  iwouldnt have to put the data attribute anymore, it automatically inherit by its parent

Great plugin, thanks

**Comment by bosz** [comment]
Yea, great plugin they got here. I have that same question here. My images have varying widths and heights so will like it to inherit from parent (fill parent container) so that it does not have overlapping issues on mobile. 

Anyone got the response please?

**Comment by zafree** [comment]
@squalvj @bosz We pass the original width and height of the image to accurately calculate its aspect ratio. This helps us block the exact area before loading the blur canvas, preventing any browser disruptions. 

Apologies for the long delay in responding. We've just released a new version. Check it out and let us know your thoughts.
